[tool.poetry]
name = "unibox"
version = "0.1.4"
description = "one toolbox to rule'em all"
authors = ["yada <trojblue@gmail.com>"]
license = "GPL-3.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
click = "^8.1.5"
tomli = "^2.0.1"
omegaconf = "^2.3.0"
pillow = "^10.0.0"
tqdm = "^4.65.0"
colorlog = "^6.7.0"
pandas = "^2.0.3"
pyarrow = "^12.0.1"

[tool.poetry.scripts]
unibox = 'unibox.cli:cli'

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
